@Library('jenkins-shared-library') _

pipeline {

    agent {
        label 'agent-1'
    }

    environment {
        AWS_REGION   = 'us-east-1'
        ECR_REGISTRY = '369343500508.dkr.ecr.us-east-1.amazonaws.com'
        IMAGE_NAME   = 'cart-service'
    }

    stages {

        stage('Code Checkout') {
            steps {
                cloneRepo(
                    'https://github.com/tusharyadav235/Cloud-Native-E-Commerce-Microservices-Platform.git',
                    'main'
                )
            }
        }
        
        stage('Build') {
            steps {
                mavenBuild('cart-service')
            }
        }

        stage('Unit Test') {
            steps {
                mavenTest('cart-service')
            }
        
            post {
                always {
                    junit 'cart-service/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Package') {
            steps {
                mavenPackage('cart-service')
            }
        }

        stage('SonarQube Analysis') {
            steps {
                sonarAnalysis('cart-service')
            }
        }

        stage('Quality Gate') {
            steps {
                qualityGate()
            }
        }

        stage('Dependency Check') {
            steps {
                dependencyCheck('cart-service')
            }
        }

        stage('Docker Build') {
            steps {
                dockerBuild(
                    'cart-service',
                    "${IMAGE_NAME}",
                    "${IMAGE_TAG}"
                )
            }
        }

        stage('Image Scan') {
            steps {
                trivyScan(
                    "${IMAGE_NAME}",
                    "${IMAGE_TAG}"
                )
            }
        }

        stage('AWS Authentication') {
            steps {
                awsAuthentication()
            }
        }

        stage('Authenticate Docker to ECR') {
            steps {
                ecrLogin(
                    "${AWS_REGION}",
                    "${ECR_REGISTRY}"
                )
            }
        }

        stage('Tag Image') {
            steps {
                tagEcrImage(
                    "${IMAGE_NAME}",
                    "${IMAGE_TAG}",
                    "${ECR_REGISTRY}"
                )
            }
        }

        stage('Push Image to ECR') {
            steps {
                pushEcrImage(
                    "${ECR_REGISTRY}",
                    "${IMAGE_NAME}",
                    "${IMAGE_TAG}"
                )
            }
        }

        stage('Promote to Dev') {
            steps {
                promoteToDev(
                    'cart-service',
                    'tusharyadav235/cloud-native-ecommerce-gitops',
                    'main',
                    "${IMAGE_NAME}",
                    "${IMAGE_TAG}",
                    "${ECR_REGISTRY}"
                )
            }
        }

        stage('Production Approval') {
            steps {
                productionApproval('cart-service')
            }
        }

        stage('Promote to Production') {
            steps {
                promoteToProduction(
                    'cart-service',
                    'tusharyadav235/cloud-native-ecommerce-gitops',
                    "${IMAGE_NAME}",
                    "${IMAGE_TAG}",
                    "${ECR_REGISTRY}"
                )
            }
        }
    }

    post {
        success {
            echo """
            CI/CD pipeline completed successfully.

            Application : ${IMAGE_NAME}
            Image Tag   : ${IMAGE_TAG}
            """
        }
        failure {
            echo """
            Pipeline failed.
            Check the failed stage and Jenkins console logs.
            """
        }
        always {
            echo "Cleaning Jenkins workspace"
            cleanWs()
        }
    }
}