apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  # Add your non-sensitive configuration variables here
  DB_URL: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/ecommerce"
  DB_USER: "ecommerce_user"
  # SPRING_PROFILES_ACTIVE: "prod"
