resources:
  - ../../base

configMapGenerator:
  - name: db-config
    literals:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-dev.db:5432/ecommerce

secretGenerator:
  - name: db-credentials
    literals:
      - SPRING_DATASOURCE_USERNAME=devuser
      - SPRING_DATASOURCE_PASSWORD=devpassword

namePrefix: dev-
